In [5]:
import numpy as np
from tests import *

In [18]:
def MaxReward(arr):
    maximum_reward = arr.copy()
    n = maximum_reward.shape[0]
    for i in range(n-1):
        for j in range(i, n-i):
            print(maximum_reward[i:i+2,i:i+2])
        break
    return 0

In [19]:
tests = load_tests(file_path="snails_test.json")
tests[-1].arr

array([[ 0,  3,  1, -1,  7,  2],
       [ 3,  1, -1, 12, -1,  0],
       [ 1, -1,  0,  4, -2,  2],
       [-1, 12,  4,  1,  0, -1],
       [ 7, -1, -2,  0,  0,  1],
       [ 2,  0,  2, -1,  1,  5]])

In [20]:
MaxReward(tests[-1].arr)

[[0 3]
 [3 1]]
[[0 3]
 [3 1]]
[[0 3]
 [3 1]]
[[0 3]
 [3 1]]
[[0 3]
 [3 1]]
[[0 3]
 [3 1]]


0